repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [pre-commit]
        language: python
        entry: pytest --cov
        types: [python]
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [--unsafe-fixes, --fix, --show-fixes, --no-cache, --preview, --config=pyproject.toml]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: '(src)/.*\.py$'

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
ci:
  autoupdate_schedule: monthly
