sparksession_ops = [
    "active",
    "builder.appName",
    "builder.config",
    "builder.enableHiveSupport",
    "builder.getOrCreate",
    "builder.master",
    "builder.remote",
    "addArtifact",
    "addArtifacts",
    "addTag",
    "catalog",
    "clearTags",
    "conf",
    "createDataFrame", # must be converted
    "dataSource",
    "getActiveSession",
    "getTags",
    "interruptAll",
    "interruptOperation",
    "interruptTag",
    "newSession",
    "profile",
    "removeTag",
    "range",
    "read", # create reader 
    "readStream",
    "sparkContext",
    "sql", # must be converted
    "stop",
    "streams",
    "table", # show all registred tables
    "tvf",
    "udf",
    "udtf",
    "version", # polars version
    "is_remote",
    "builder.create",
    "clearProgressHandlers",
    "client",
    "copyFromLocalToFs",
    "registerProgressHandler",
    "doremoveProgressHandler",
]