name: linting

on:
  - workflow_call

jobs:
  linting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[lint]'
      - name: ⚠️ Important to read ⚠️
        run: |
          echo "Linting prerequisites:"
          echo "Linting job started. Please ensure there are no linting errors before merging the PR."
          echo "To fix linting errors locally, run the following commands:"
          echo "1. Install linting dependencies: pip install '.[lint]'"
          echo "2. Install pre-commit hooks: pre-commit install"
          echo "3. Run pre-commit on all files: pre-commit run --all-files"
      - name: run black
        run: black --diff src
      - name: run ruff
        run: ruff check --fix --unsafe-fixes --preview --exit-zero --show-files --diff --config=pyproject.toml
